# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 474f3934fccfdf1d62d9f0a6527ed51e814b815269f0c3daf540710a0ab965b31b391a4ae0f56f209cd8e3a0372a29de39f9d949b57fd73f6d7e2128f0a0e740

test:
  secret_key_base: 0f9ebdbe491cb5b9b1b0d40d3874305c71eb5f3037d170d719437db59dba775d13eacc815a11ce2fc82d54f6975b77feddd2803b90ed6ceed4618b56c2536667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
